### ISSUE TITLE
Crash app at first time open

### ISSUE THREAD

**Issue by 159159951** [YarikSOffice/LanguageTest#3]
App crash at first time open:
Here is my logcat:
`01-08 08:28:54.426 26004-26004/com.yariksoffice.languagetest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.yariksoffice.languagetest, PID: 26004
                                                                               java.lang.RuntimeException: Unable to resume activity {com.yariksoffice.languagetest/com.yariksoffice.languagetest.ui.MainActivity}: java.lang.IllegalArgumentException: Unsupported language
                                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                                Caused by: java.lang.IllegalArgumentException: Unsupported language
                                                                                   at com.yariksoffice.languagetest.ui.BaseActivity.getLanguageDrawable(BaseActivity.java:129)
                                                                                   at com.yariksoffice.languagetest.ui.BaseActivity.updateInfo(BaseActivity.java:101)
                                                                                   at com.yariksoffice.languagetest.ui.BaseActivity.showResourcesInfo(BaseActivity.java:76)
                                                                                   at com.yariksoffice.languagetest.ui.BaseActivity.onResume(BaseActivity.java:70)
                                                                                   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
                                                                                   at android.app.Activity.performResume(Activity.java:6766)
                                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713) 
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
`

**Comment by YarikSOffice** [comment]
@159159951 Nice catch! Should be fixed now.
Thank you for the report!
